"use client"

import { useMemo, useState } from "react"
import { ChevronDown, Mountain, ArrowRight, Search } from "lucide-react"
import { Badge } from "@/components/ui/badge"

const faqSections = [
  { title: "What is the Rocktober Challenge?", body: "This completely free challenge runs throughout October. Choose a tier based on your age, gender, and estimated climbing ability, then earn points by logging checkpoints, tops, and completed challenges. Challenges are worth more points, and each completed challenge can only be logged once. Use the QR codes posted by the wall to log your progress." },
  { title: "What is a checkpoint?", body: "The rockwall has nine walls labeled 1 through 9. Each wall has checkpoints at approximately one-third and two-thirds of the way up. Reach and grab a hold at or above the number to reach that checkpoint. When logging a climb, record only the farthest point you reached; if you top a wall, do not also log its checkpoints. A checkpoint challenge can still be logged if you have already topped that wall." },
  { title: "What counts as the top?", body: "On walls 6 and 7 (the autobelays), the top is touching the bottom of the autobelay with one hand in a controlled way. When rainbowing, the top is hitting the number at the top of the wall. When following a route, the top means grabbing the literal top of the wall with two hands, including when a route says “nats off.”" },
  { title: "When can I climb?", body: "Certified climbers, or climbers with a certified belayer, may climb whenever the YMCA is open. Check the Rock Climbing Info Board for class times and open climbs. Open climbs are posted Saturdays from 12–1pm, when staff belay participants for free. If you are not certified, attend an open climb or sign up for the belay class or autobelay-only class." },
  { title: "What do I need to climb?", body: "You must have signed a 2026 waiver, wear close-toed shoes, and have access to a harness. Staff can provide harnesses during open climbs, or you can get one at the front desk by showing your certification card." },
  { title: "What are route cards, nats off, and volumes?", body: "Route cards identify the hold color and difficulty. Difficulty increases as the number rises (for example, 5.8 < 5.9 < 5.10a < 5.10d < 5.11a). “Nats off” means natural wall features cannot be pulled on; “nats off for hands” still allows pushing on the wall. Volumes count only when a route hold is mounted to them or the route card says they count." },
  { title: "How do points and prizes work?", body: "Harder walls, routes, and challenges are worth more points, and getting farther earns more points. In routes categories, after a route is logged as a top five times, future logs are worth half as much. First place earns bragging rights, while specific completed challenges earn prizes available at the front desk a few days after reporting." },
  { title: "Can I join late or complete all my challenges?", body: "Yes. Anyone can join after October 1 and still earn points and prizes. If you complete every challenge in your tier, keep logging tops and checkpoints; more challenges may be added during the month." },
]

const challengeGroups = [
  { tier: "4–6 years", subtitle: "Wall Climbs", items: ["Checkpoint 1 on walls #9 and #1", "Checkpoint 1 on walls #6 and #7", "Checkpoint 2 on walls #9 and #1", "Top #9 in under 3 minutes", "Top #9 without purple holds", "Top #8 without blue holds", "Top #7 without unicorn holds", "Top #6 without purple holds", "Top #5 without yellow holds", "Top #4 without black holds", "Top #3 without orange holds", "Top #2 without pink holds", "Top #1 without purple holds"] },
  { tier: "7–9 years", subtitle: "Wall Climbs", items: ["Top walls #9 and #1", "Checkpoint 2 on walls #6 and #7", "Checkpoint 1 on walls #2 and #8", "Top #9 in under 2 minutes", "Top #1 in under 2 minutes", "Top #9 without purple holds", "Top all the Walls", "Climb to the top of #8 without using blue holds", "Climb to the top of #7 without using unicorn holds", "Climb to the top of #6 without using purple holds", "Climb to the top of #5 without using yellow holds", "Climb to the top of #4 without using black holds", "Climb to the top of #3 without using oranges holds", "Climb to the top of #2 without using pink holds", "Climb to the top of #1 without using purple holds"] },
  { tier: "10–12 years", subtitle: "Wall Climbs", items: ["Top #9 in under 1 minute", "Top #9 without green holds", "Top #1 without purple holds", "Top both autobelays", "Checkpoint 2 on walls #2 and #8", "Checkpoint 1 on walls #3, #4, and #5", "Top all the walls", "Climb to the top of Wall #8 without using white holds", "Climb to the top of Wall #7 without using gray holds", "Climb to the top of Wall #6 without using purple holds", "Climb to the top of Wall #5 without using yellow holds", "Climb to the top of Wall #4 without using black holds", "Climb to the top of Wall #3 without using oranges holds", "Climb to the top of Wall #2 without using pink holds"] },
  { tier: "13–18 years", subtitle: "Wall Climbs", items: ["Climb up and down an autobelay without falling", "Top #9 in under 30 seconds", "Top walls #9, #1, and #2", "Top both autobelays (#6 and #7)", "Top wall #7 without unicorn holds", "Top wall #6 without gray holds", "Checkpoint 2 on walls #3, #4, and #5", "Climb #9 using only blue and gray holds", "Climb #1 using only gray/brown and orange", "Top all the walls"], routes: ["All routes on wall #6", "All routes on wall #7", "Up and down an autobelay using a route of your choice", "A 5.8 without using every other hold", "A 5.9 without using every other hold", "Smurf and Turf under 1 minute", "Aquaman under 2 minutes", "Trick or Yeet under 30 seconds", "All 5.8s to the top", "Checkpoint 2 on all 5.9s", "All red routes", "All 5.9s to the top", "Checkpoint 2 on all 5.10a’s", "All white routes under 5.10b", "All green routes 5.10a and lower", "All 5.10a’s to the top", "Checkpoint 1 on all 5.10b’s", "All blue routes", "Night Fury to the top", "Sher-Bert and Ernie on wall 7 to the top"] },
  { tier: "19+ years", subtitle: "Wall Climbs", items: ["Top walls #9, #1, and #2", "Top both autobelays", "Top wall #7 without unicorn holds", "Top wall #6 without gray holds", "Up and down an autobelay without falling", "Checkpoint 1 on walls #3, #4, and #5", "Checkpoint 2 on walls #2 and #8", "Climb #9 using only blue and gray holds", "Climb #1 using only gray/brown and orange", "Top all the walls"], routes: ["Up and down an autobelay using a route of your choice", "Smurf and Turf under 30 seconds", "Aquaman under 1 minute", "Trick or Yeet under 30 seconds", "All 5.8s to the top", "A 5.8 without using every other hold", "A 5.9 without using every other hold", "Checkpoint 2 on all 5.9s", "All red routes", "All 5.9s to the top", "All white routes under 5.10b", "All green routes 5.10a and lower", "Checkpoint 2 on all 5.10a’s", "All 5.10a’s to the top", "All blue routes", "All yellow routes", "Night Fury to the top", "Sher-Bert and Ernie on wall 7 to the top"] },
  { tier: "19+ years", subtitle: "Routes · 5.10a+", items: ["All 5.9 routes", "Up and down an autobelay using a route of your choice", "A 5.8 without using every other hold", "A 5.9 without using every other hold", "All routes on walls #6 and #7", "A 5.10a under 30 seconds", "A 5.10b or higher under 30/45 seconds (men/women)", "Top all 5.10a’s", "A 5.10a using only half the holds", "All purple routes", "All blue routes", "Checkpoint 2 on all 5.10b’s", "Top all 5.10b’s", "All orange routes", "Checkpoint 2 on all 5.10c’s", "Top all 5.10c’s", "Checkpoint 1 on all 5.10d’s or harder", "All white routes (excluding Miracle Whip on #8)", "Top two routes rated 5.10d or harder", "All pink routes", "One wall using only natural features", "Every single route below 5.10d"] },
]

const general = ["Bring someone climbing who has never been", "Submit a picture in a Halloween costume", "Climb the secret routes or walls with a secret route", "Traverse the entire wall while keeping your feet below the black line", "Climb at NW at least once during October"]

function ChallengeList({ title, items }: { title: string; items: string[] }) {
  return <div className="flex flex-col gap-3"><h4 className="text-sm font-bold uppercase tracking-widest text-primary">{title}</h4><ul className="grid list-none gap-2 sm:grid-cols-2">{items.map((item) => <li key={item} className="flex gap-3 rounded-xl border border-border/70 bg-background/60 px-4 py-3 text-sm leading-relaxed"><Mountain aria-hidden="true" className="mt-0.5 size-4 shrink-0 text-primary" />{item}</li>)}</ul></div>
}

export function RocktoberPage() {
  const [activeTier, setActiveTier] = useState("All tiers")
  const [query, setQuery] = useState("")
  const filtered = useMemo(() => challengeGroups.filter((group) => activeTier === "All tiers" || group.tier === activeTier).map((group) => ({ ...group, items: [...group.items, ...(group.routes ?? [])].filter((item) => item.toLowerCase().includes(query.toLowerCase())) })), [activeTier, query])
  return <div className="min-h-screen bg-background">
    <header className="sticky top-0 z-10 border-b border-border/70 bg-background/90 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4"><a href="#top" className="flex items-center gap-3 font-display text-xl tracking-wide"><span className="grid size-9 place-items-center rounded-xl bg-primary text-primary-foreground"><Mountain /></span><span>ROCKTOBER <span className="text-primary">CHALLENGE</span></span></a><nav className="hidden gap-6 text-sm font-medium sm:flex"><a href="#rules" className="hover:text-primary">Rules & FAQ</a><a href="#challenges" className="hover:text-primary">Challenges</a></nav></div></header>
    <main id="top"><section className="relative overflow-hidden border-b border-border/70"><div className="mx-auto grid max-w-6xl gap-10 px-5 py-20 md:grid-cols-[1.1fr_.9fr] md:items-center md:py-28"><div><Badge className="mb-5 rounded-full px-3 py-1">October · North YMCA</Badge><h1 className="max-w-3xl font-display text-5xl tracking-wide sm:text-7xl">ROCKTOBER <span className="text-primary">CHALLENGE</span><br /><span className="font-sans text-4xl font-black tracking-tight sm:text-6xl">Climb more. <span className="text-primary">Challenge yourself.</span></span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-muted-foreground">A completely free month-long climbing challenge for every age and ability. Pick your tier, try new climbs, and earn points all October long.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#challenges" className="inline-flex items-center gap-2 rounded-xl bg-primary px-5 py-3 font-semibold text-primary-foreground">Explore challenges <ArrowRight /></a><a href="#rules" className="rounded-xl border border-border px-5 py-3 font-semibold">Read the rules</a></div></div><div className="rounded-[2rem] bg-primary p-8 text-primary-foreground shadow-2xl shadow-primary/20"><p className="text-sm font-semibold uppercase tracking-widest opacity-80">How it works</p><ol className="mt-7 flex flex-col gap-6">{["Choose the tier that fits you", "Climb walls, routes, and checkpoints", "Log your progress with the wall QR codes"].map((step, i) => <li key={step} className="flex gap-4"><span className="grid size-8 shrink-0 place-items-center rounded-full bg-primary-foreground font-bold text-primary">{i + 1}</span><span className="pt-1 font-medium">{step}</span></li>)}</ol></div></div></section>
    <section id="rules" className="mx-auto max-w-6xl scroll-mt-20 px-5 py-20"><div className="mb-10 max-w-2xl"><p className="text-sm font-bold uppercase tracking-widest text-primary">Start here</p><h2 className="mt-2 text-4xl font-black tracking-tight">Rules & FAQs</h2><p className="mt-3 text-muted-foreground">Everything you need to know before you step onto the wall.</p></div><div className="grid gap-3 md:grid-cols-2">{faqSections.map((faq) => <details key={faq.title} className="group rounded-2xl border border-border bg-card px-5 py-4"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 font-bold">{faq.title}<ChevronDown className="transition-transform group-open:rotate-180" /></summary><p className="mt-4 border-t border-border pt-4 text-sm leading-7 text-muted-foreground">{faq.body}</p></details>)}</div></section>
    <section id="challenges" className="scroll-mt-20 bg-muted/40 px-5 py-20"><div className="mx-auto max-w-6xl"><div className="mb-10 flex flex-col gap-6 md:flex-row md:items-end md:justify-between"><div><p className="text-sm font-bold uppercase tracking-widest text-primary">Pick your tier</p><h2 className="mt-2 text-4xl font-black tracking-tight">The challenge list</h2></div><div className="relative w-full md:max-w-xs"><Search className="absolute left-3 top-3 text-muted-foreground" /><input aria-label="Search challenges" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search challenges" className="w-full rounded-xl border border-border bg-background py-2.5 pl-10 pr-4 text-sm outline-none ring-primary focus:ring-2" /></div></div><div className="mb-10 flex flex-wrap gap-2">{["All tiers", ...new Set(challengeGroups.map((group) => group.tier))].map((tier) => <button key={tier} onClick={() => setActiveTier(tier)} className={`rounded-full border px-4 py-2 text-sm font-semibold transition-colors ${activeTier === tier ? "border-primary bg-primary text-primary-foreground" : "border-border bg-background hover:border-primary"}`}>{tier}</button>)}</div><div className="flex flex-col gap-8">{filtered.map((group) => <article key={`${group.tier}-${group.subtitle}`} className="rounded-3xl border border-border bg-card p-6 shadow-sm md:p-8"><div className="mb-6 flex flex-wrap items-center gap-3"><h3 className="text-2xl font-black">{group.tier}</h3><Badge variant="secondary">{group.subtitle}</Badge><span className="text-sm text-muted-foreground">{group.items.length} challenges</span></div><ChallengeList title={group.subtitle} items={group.items} />{group.routes && !query && <div className="mt-8"><ChallengeList title="Routes" items={group.routes} /></div>}</article>)}<article className="rounded-[2rem] border-2 border-dashed border-secondary/60 bg-secondary/10 p-6 shadow-sm md:p-8"><div className="mb-5 flex flex-wrap items-center gap-3"><h3 className="font-display text-3xl tracking-wide text-secondary">Generic / Other</h3><Badge variant="secondary" className="rounded-full">For everyone</Badge></div><div className="mt-5"><ChallengeList title="Everyone" items={general} /></div></article></div></div></section></main><footer className="border-t border-border px-5 py-8 text-center text-sm text-muted-foreground">North YMCA · Rocktober Challenge · October</footer>
  </div>
}
